
apikey: VAULT.secret/services/general/graph-api
bucket: fronts
couchbase: VAULT.secret/services/graph-api/production
query: "select meta().id from `fronts` where meta().id LIKE 'section-front_%'"
sasl: VAULT.secret/services/graph-api/production
sitecode: SITE
url:
  api: http://jsonimo-api.domain.com/api/v1/{FRONTNAME}?readmodel=push-publishing
  diagapi: http://jsonimo-diagnostic-api.domain.com/api/v1/aggregates/{FRONTNAME}?model=push-publishing
  graphql: https://graph-api.domain.com/v1/graphql?type=asset&query=%7B%20front%28id%3A%20%22{FRONTNAME}%22%29%20%7B%20id%20displayName%20layoutModules%20%7B%20moduleDisplayName%20contents%20%7B%20asset%20%7B%20contentSourceCode%20id%20type%20headline%20%7D%20%7D%20%7D%20%7D%20%7D%20
  presapi: http://pres-api.domain.com/v4/fronts/{SITECODE}/{FRONTNAME}?consumer=test&merged=true
