#!/bin/bash
#
# Generate Bearer token for Google Cloud Platform
#

help() {
    echo -e "\nUsage: ${0##*/} <app> <noc|staging> [<vault-key>] [<iam-email>]\n"
    exit 1
}

base64url() {
    base64 | tr '+/' '-_' | tr -d '='
}

app=$1; shift
if [ -z "$app" ]; then
    help
fi
noc=${1:-staging}; shift
vault=${1:-pubsub_subscriber_private_key}; shift
email=${1:-$app@gannett-product-$noc.iam.gserviceaccount.com}

pem=/tmp/$app.pem
echo -e $(vault read secret/paas-api/$app/$noc | grep $vault | cut -f2-) > $pem

jwt_head=$(echo -n '{"alg":"RS256","typ":"JWT"}' | base64url)

jwt_data=$(echo "{\"iss\":\"$email\",\
\"scope\":\"https://www.googleapis.com/auth/pubsub\",\
\"aud\":\"https://www.googleapis.com/oauth2/v4/token\",\
\"exp\":$(gdate +%s --date=+600\ seconds),\
\"iat\":$(gdate +%s)}" | base64url)

jwt_sign=$(echo -n "${jwt_head}.${jwt_data}" | openssl dgst -sha256 -sign $pem | base64url )

out=$(curl -s -X POST https://www.googleapis.com/oauth2/v4/token \
    --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer" \
    --data-urlencode "assertion=${jwt_head}.${jwt_data}.${jwt_sign}")

echo $out | jq
echo $out | jq -r '.access_token'
