#!/bin/bash
#
# Quick change directory to go/src directories
# set alias gcd=". gocd"
#

repo=$1
src=/Users/kklee/repos/go/src

IFS=/
set -- $repo
unset IFS

base=github.com
case $# in
    3)  cd $src/$repo ;;
    2)  cd $src/$base/$repo ;;
    *)  owners="GannettDigital ikenticus"
        for work in $owners; do
            [ -d $src/$base/$work/$repo ] && cd $src/$base/$work/$repo
        done
esac
