#!/bin/bash
#
# Attempting to automatically retrieve all the necessary environment variables before running golang 
#

SCRIPT=${1:-main.go}

### ENV: Static
REGION=us-east-1
VAULT_URL=$VAULT_ADDR
CONSUL_URL=https://consul.service.gciconsul.com:8443

### ENV: Overrides
var=ENVIRONMENT
if [ -z "$ENVIRONMENT" ]; then
    eval $var="staging"
fi
#eval echo $var=\$$var

### ENV: Vault
vault_key() {
    local KEY=$1
    BASE=${PWD##*/}
    CONFIG=$(vault read secret/paas-api/general/$BASE/$ENVIRONMENT)
    if [ $? -eq 0 ]; then
        vault read secret/paas-api/general/$BASE/$ENVIRONMENT | grep $KEY | awk '{ print $NF }'
        return
    fi
}
CONSUL_TOKEN=$(vault_key consul_acl_token)
VAULT_ROLE=$(vault_key role_id)
VAULT_SECRET=$(vault_key secret_id)

if [ $SCRIPT == "help" ]; then
    #ls k8/deployment/${ENVIRONMENT}*.json
    MIN=$( pcregrep '"name": "[A-Z_]+"' k8/deployment/${ENVIRONMENT}*.json \
            | cut -d: -f2 | sed 's/^.*"\(.*\)".*$/\1/' )
    echo -e "\nMinimal ENV variables needed:\n${MIN}\n"
    exit 0
fi

ENVIRONMENT=$ENVIRONMENT \
REGION=$REGION \
CONSUL_URL=$CONSUL_URL \
VAULT_URL=$VAULT_URL \
CONSUL_TOKEN=$CONSUL_TOKEN \
VAULT_ROLE_ID=$VAULT_ROLE \
VAULT_SECRET_ID=$VAULT_SECRET \
go run $SCRIPT

