#!/bin/bash
#
# KS: Kubernetes Switch shortcut between clusters
#
# created before kubectx was discovered
#

help() {
    kubectl config get-contexts
    echo -e "\nUsage: ${0##*/} <app-name>\n"
    exit 1
}

app=$1
if [ -z "$app" ]; then
    help
fi

names=$(kubectl config view | grep -A4 -- '^- context' | grep name:  | awk '{ print $NF }')
context=$(echo $names | tr [[:space:]] "\n" | grep $app)

test=$(echo $context)
if [ -z "${test//* */}" ]; then
    IFS=-
    set -- $app
    unset IFS
    context=$(echo $names | tr [[:space:]] "\n" | egrep ".*${1}.*-.*${2}.*")
    if [ -z "$context" ]; then
        echo Invalid app: $context
        help
    fi
fi

kubectl config use-context $context
ns=$(kubectl config get-contexts | grep ^* | awk '{ print $NF }')
kubectl config use-context $context --namespace=$ns
echo kubectl config use-context $context $ns
#kubectl cluster-info
#kubectl proxy
