#!/bin/bash
#
# Refresh repo
#

branches=$@
cd ~/repos
for i in cs-oly* cs-sports*; do
    echo -e " \n===== $i"
    cd $i
    [ "$(git rev-parse --abbrev-ref HEAD)" != "master" ] && git checkout master
    [ $(git branch | wc -l) -gt 1 ] && git branch
    git pull
    if [ ! -z "$branches" ]; then
        for branch in $branches; do
            [ ! -z "$(git branch | grep $branch)" ] && git branch -D $branch
        done
    fi
    cd ..
done
